[package]
name = "vault"
version = "0.1.0"
edition = "2021"
author = "Shubham singh		<github: github.com/shubhexists>"
about = "A simplified version control system built in Rust for local files, quite similar to how git functions."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
